"""Oakland Open Data — code-mode runtime API.

This module is the agent-facing surface for the Oakland Data MCP under
"code mode". A script generated by the model can do:

    from mcp.oakland import search_datasets, get_dataset_info, query_dataset

    hits = search_datasets("crime")
    ds = hits[0]["id"]
    rows = query_dataset(
        ds,
        select="crimetype, count(*) as cnt",
        group="crimetype",
        order="cnt DESC",
        limit=10,
    )
    for r in rows:
        print(f"{r['crimetype']}: {r['cnt']}")

Design notes:

* Functions are SYNCHRONOUS. They wrap the async `oakland_mcp.tools` /
  `oakland_mcp.socrata` layer with `asyncio.run` so the agent can write plain
  Python without `await`.
* Returns are STRUCTURED data (lists of dicts, single dicts) rather than the
  pre-formatted markdown strings the MCP tool surface returns. The agent can
  iterate, sum, and transform the results in code.
* Errors raise `OaklandAPIError` whose message contains the same recovery
  hints the MCP layer surfaces (location sub-columns, etc.) so a stderr
  traceback is enough for the agent to self-correct on the next attempt.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from typing import Any

import httpx

from .. import socrata
from ..config import (
    DEFAULT_PREVIEW_LIMIT,
    DEFAULT_QUERY_LIMIT,
    DEFAULT_SEARCH_LIMIT,
    MAX_LIMIT,
)


__all__ = [
    "OaklandAPIError",
    "search_datasets",
    "list_categories",
    "get_dataset_info",
    "preview_dataset",
    "query_dataset",
    "get_column_stats",
]


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------

class OaklandAPIError(Exception):
    """Raised when the Socrata API returns an error.

    The exception message contains the upstream status code, response body,
    and a recovery hint where applicable (e.g., for `location`-type columns).
    Catching this in your script and printing it is enough for the next
    iteration to self-correct.
    """

    def __init__(
        self,
        status_code: int,
        body: str,
        hint: str | None = None,
    ) -> None:
        self.status_code = status_code
        self.body = body
        self.hint = hint
        msg = f"Socrata API error ({status_code}): {body}"
        if hint:
            msg += f"\nHint: {hint}"
        super().__init__(msg)


_LOCATION_HINT = (
    "If you filtered a `location`-type column with LIKE/=, that won't work — "
    "location is a composite type. Use sub-columns instead, e.g. "
    "`stname_address LIKE '%PARK%'`. Sub-columns: `_address`, `_city`, `_state`, "
    "`_zip`, `_latitude`, `_longitude`. Call `get_dataset_info(dataset_id)` to "
    "see column types."
)


def _run(coro):
    """Run an async coroutine to completion in a fresh event loop."""
    return asyncio.run(coro)


def _wrap_http_error(e: httpx.HTTPStatusError) -> OaklandAPIError:
    body = e.response.text
    hint = _LOCATION_HINT if "location" in body.lower() or "type-mismatch" in body.lower() else None
    return OaklandAPIError(e.response.status_code, body, hint)


def _clamp(value: int, lo: int, hi: int, default: int) -> int:
    if not isinstance(value, int) or value < lo or value > hi:
        return default
    return value


# ---------------------------------------------------------------------------
# search_datasets
# ---------------------------------------------------------------------------

def search_datasets(
    query: str,
    category: str | None = None,
    limit: int = DEFAULT_SEARCH_LIMIT,
) -> list[dict[str, Any]]:
    """Search Oakland's open data portal by keyword.

    Args:
        query: Keywords (e.g. "crime", "trees", "311").
        category: Optional category filter (e.g. "Public Safety").
        limit: Max results, 1-50, default 10.

    Returns:
        List of dataset summaries, each a dict with:
          - id: Socrata dataset id (e.g. "ym6k-rx7a")
          - name: human-readable title
          - description: dataset description (may be empty)
          - category: domain category
          - type: "dataset", "map", etc.
          - updated_at: ISO date string (yyyy-mm-dd) or empty
          - total_matches: total match count for the query (same on every row)

    Raises:
        OaklandAPIError on upstream failure.
    """
    limit = _clamp(limit, 1, 50, DEFAULT_SEARCH_LIMIT)

    try:
        data = _run(socrata.discovery_search(
            query=query, category=category or "", limit=limit,
        ))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e

    total = data.get("resultSetSize", 0)
    out: list[dict[str, Any]] = []
    for item in data.get("results", []):
        res = item.get("resource", {}) or {}
        cls = item.get("classification", {}) or {}
        out.append({
            "id": res.get("id", ""),
            "name": res.get("name", ""),
            "description": (res.get("description") or "").strip(),
            "category": cls.get("domain_category", ""),
            "type": res.get("type", "dataset"),
            "updated_at": (res.get("updatedAt") or "")[:10],
            "total_matches": total,
        })
    return out


# ---------------------------------------------------------------------------
# list_categories
# ---------------------------------------------------------------------------

def list_categories() -> list[dict[str, Any]]:
    """List dataset categories on the Oakland portal.

    Returns:
        List of dicts {category, count}, sorted by count descending.

    Raises:
        OaklandAPIError on upstream failure.
    """
    try:
        data = _run(socrata.discovery_search(query="", limit=200))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e

    counts: dict[str, int] = {}
    for item in data.get("results", []):
        cat = (item.get("classification") or {}).get("domain_category", "")
        if cat:
            counts[cat] = counts.get(cat, 0) + 1

    return [
        {"category": cat, "count": n}
        for cat, n in sorted(counts.items(), key=lambda x: x[1], reverse=True)
    ]


# ---------------------------------------------------------------------------
# get_dataset_info
# ---------------------------------------------------------------------------

def get_dataset_info(dataset_id: str) -> dict[str, Any]:
    """Get metadata + column schema for one dataset.

    Args:
        dataset_id: Socrata dataset id (e.g. "ym6k-rx7a").

    Returns:
        Dict with:
          - id, name, description, category, attribution
          - row_count: int (or None if unknown)
          - updated_at: yyyy-mm-dd string (or "" if unknown)
          - columns: list of dicts:
              - name: field name to use in queries
              - type: Socrata data type ("text", "number", "location", ...)
              - description: column description (may be empty)
              - is_location: True if this is a composite location column
              - sub_columns: list of sub-column names available when is_location
                (e.g. ["_address", "_city", "_state", "_zip", "_latitude",
                "_longitude"]). Only populated for location columns. To filter
                a location column with LIKE, use `<name>_address`, NOT `<name>`.
          - location_columns: list of names of all location-type columns in
            this dataset (convenience field for quick checks).

    Raises:
        OaklandAPIError on upstream failure.
    """
    if not dataset_id:
        raise ValueError("dataset_id is required")

    try:
        meta = _run(socrata.get_metadata(dataset_id))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e

    updated = meta.get("rowsUpdatedAt") or meta.get("viewLastModified", "")
    if isinstance(updated, (int, float)):
        updated = datetime.fromtimestamp(updated, tz=timezone.utc).strftime("%Y-%m-%d")
    elif isinstance(updated, str) and len(updated) >= 10:
        updated = updated[:10]
    else:
        updated = ""

    row_count = meta.get("rowCount") or meta.get("rows")
    try:
        row_count = int(row_count) if row_count is not None else None
    except (TypeError, ValueError):
        row_count = None

    columns: list[dict[str, Any]] = []
    location_columns: list[str] = []
    for col in meta.get("columns", []) or []:
        col_name = col.get("fieldName") or col.get("name", "")
        col_type = col.get("dataTypeName", "unknown")
        is_loc = col_type == "location"
        entry: dict[str, Any] = {
            "name": col_name,
            "type": col_type,
            "description": (col.get("description") or "").strip(),
            "is_location": is_loc,
            "sub_columns": [],
        }
        if is_loc:
            entry["sub_columns"] = [
                f"{col_name}_address",
                f"{col_name}_city",
                f"{col_name}_state",
                f"{col_name}_zip",
                f"{col_name}_latitude",
                f"{col_name}_longitude",
            ]
            location_columns.append(col_name)
        columns.append(entry)

    return {
        "id": dataset_id,
        "name": meta.get("name", ""),
        "description": (meta.get("description") or "").strip(),
        "category": meta.get("category", ""),
        "attribution": meta.get("attribution", ""),
        "row_count": row_count,
        "updated_at": updated,
        "columns": columns,
        "location_columns": location_columns,
    }


# ---------------------------------------------------------------------------
# preview_dataset
# ---------------------------------------------------------------------------

def preview_dataset(
    dataset_id: str,
    limit: int = DEFAULT_PREVIEW_LIMIT,
) -> list[dict[str, Any]]:
    """Return a small sample of unfiltered rows.

    Args:
        dataset_id: Socrata dataset id.
        limit: Number of rows, 1-50, default 10.

    Returns:
        List of row dicts (raw Socrata field shape).

    Raises:
        OaklandAPIError on upstream failure.
    """
    if not dataset_id:
        raise ValueError("dataset_id is required")
    limit = _clamp(limit, 1, 50, DEFAULT_PREVIEW_LIMIT)

    try:
        return _run(socrata.soda_query(dataset_id, {"$limit": str(limit)}))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e


# ---------------------------------------------------------------------------
# query_dataset
# ---------------------------------------------------------------------------

def query_dataset(
    dataset_id: str,
    select: str | None = None,
    where: str | None = None,
    order: str | None = None,
    group: str | None = None,
    having: str | None = None,
    limit: int = DEFAULT_QUERY_LIMIT,
    offset: int = 0,
) -> list[dict[str, Any]]:
    """Run a structured SoQL query.

    The server constructs the SoQL query from individual clauses — pass each
    clause separately, do NOT build a raw `$query` string.

    Args:
        dataset_id: Socrata dataset id.
        select: Columns to return, with optional aggregations.
                E.g. "crimetype, count(*) as cnt" or "address, datetime".
        where:  Filter condition.
                E.g. "crimetype = 'ROBBERY'", "datetime > '2025-01-01'".
                For location columns use sub-columns:
                "stname_address LIKE '%PARK%'".
        order:  Sort order. E.g. "datetime DESC", "cnt DESC".
        group:  Group by. E.g. "crimetype".
        having: Filter on aggregates. E.g. "count(*) > 5".
        limit:  Max rows, 1..MAX_LIMIT, default 500.
        offset: Pagination offset, default 0.

    Returns:
        List of row dicts. Aggregation results have aliased columns (e.g.
        a row like {"crimetype": "ROBBERY", "cnt": "1247"} for the example
        above).

    Raises:
        OaklandAPIError on upstream failure (the message includes a hint
        about location sub-columns when the error suggests it).
    """
    if not dataset_id:
        raise ValueError("dataset_id is required")
    limit = _clamp(limit, 1, MAX_LIMIT, DEFAULT_QUERY_LIMIT)
    offset = max(0, offset)

    params: dict[str, str] = {"$limit": str(limit), "$offset": str(offset)}
    if select:
        params["$select"] = select
    if where:
        params["$where"] = where
    if order:
        params["$order"] = order
    if group:
        params["$group"] = group
    if having:
        params["$having"] = having

    try:
        return _run(socrata.soda_query(dataset_id, params))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e


# ---------------------------------------------------------------------------
# get_column_stats
# ---------------------------------------------------------------------------

def get_column_stats(
    dataset_id: str,
    column_name: str,
) -> list[dict[str, Any]]:
    """Distinct-value frequency for one column.

    Useful for "what values exist?" — e.g. listing crime types or status codes
    before writing a filter.

    Args:
        dataset_id: Socrata dataset id.
        column_name: Field name (must match exactly; check
            `get_dataset_info(...)["columns"]`).

    Returns:
        Up to 50 rows, each a dict:
          - value: the column value
          - count: int row count for that value
          - pct: float percentage of total
        Sorted by count descending.

    Raises:
        OaklandAPIError on upstream failure (e.g. the column is a `location`
        type and can't be aggregated directly — try a sub-column).
    """
    if not dataset_id or not column_name:
        raise ValueError("dataset_id and column_name are required")

    params = {
        "$select": f"`{column_name}`, count(*) as count",
        "$group": f"`{column_name}`",
        "$order": "count DESC",
        "$limit": "50",
    }

    try:
        rows = _run(socrata.soda_query(dataset_id, params))
    except httpx.HTTPStatusError as e:
        raise _wrap_http_error(e) from e

    total = 0
    for r in rows:
        try:
            total += int(r.get("count", 0))
        except (TypeError, ValueError):
            pass

    out: list[dict[str, Any]] = []
    for r in rows:
        try:
            n = int(r.get("count", 0))
        except (TypeError, ValueError):
            n = 0
        out.append({
            "value": r.get(column_name),
            "count": n,
            "pct": (n / total * 100.0) if total else 0.0,
        })
    return out
